local o = vim.o
local bo = vim.bo
local wo = vim.wo

o.tabstop = 2
o.softtabstop = 2
o.shiftwidth = 2
vim.opt.backspace = { 'indent', 'eol', 'start' } -- Allow backspacing over newline
o.expandtab = true -- Use the appropriate number of spaces to insert a <Tab>.
o.termguicolors = false -- Enables 24-bit RGB color in the TUI
o.syntax = 'on'
o.errorbells = false
o.ignorecase = true -- Ignore case when searching
o.smartcase = true -- Override ignorecase when capital letters are typed
o.showmode = false 
bo.swapfile = false -- Don't create a swapfile for the buffer.
o.backup = false
o.undofile = true
o.undodir = vim.fn.stdpath('config') .. '/undodir'
o.incsearch = true -- Match search results while typing
o.hidden = true
o.completeopt='menuone,noinsert,noselect'
bo.autoindent = true
bo.smartindent = true
wo.number = true
wo.relativenumber = true
wo.signcolumn = 'yes'
wo.wrap = false
